# Generated by Django 3.1.12 on 2021-06-27 09:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0018_auto_20210312_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 6, 27, 9, 1, 38, 617195, tzinfo=utc)),
        ),
    ]
