# Generated by Django 3.1.12 on 2021-07-13 02:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0019_auto_20210627_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 13, 2, 46, 54, 220235, tzinfo=utc)),
        ),
    ]
