# Generated by Django 3.1.12 on 2021-07-14 09:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0021_auto_20210714_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 14, 9, 42, 57, 769064, tzinfo=utc)),
        ),
    ]
