# Generated by Django 3.1.12 on 2021-07-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerAdmin', '0020_remove_pricing_staff_basic_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(max_length=50, null=True)),
                ('customer_last_name', models.CharField(max_length=100, null=True)),
                ('customer_email', models.CharField(max_length=100, null=True)),
                ('customer_date', models.CharField(default='ok', max_length=20, null=True)),
                ('customer_picture', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.CharField(default='ok', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='occupation_adult',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='occupation_children',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_size',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_view',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
