# Generated by Django 3.1.12 on 2021-07-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerAdmin', '0021_auto_20210712_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer_date',
            field=models.DateTimeField(max_length=20, null=True),
        ),
    ]
