# Generated by Django 3.1.12 on 2021-07-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownerAdmin', '0022_auto_20210713_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='customer_picture',
        ),
    ]
