# Generated by Django 3.1.12 on 2021-07-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerAdmin', '0023_remove_customers_customer_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='customer_email',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='customer_first_name',
            new_name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='customer_date',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='customer_last_name',
        ),
        migrations.AddField(
            model_name='customers',
            name='checkin',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='checkout',
            field=models.DateField(default=None, null=True),
        ),
    ]
